org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true

# React Native
# Bundle JS into the APK even for debug builds (no Metro server needed)
bundleInDebug=true
FLIPPER_VERSION=0.182.0
reactNativeArchitectures=arm64-v8a,x86_64
newArchEnabled=false
hermesEnabled=true
IS_NEW_ARCHITECTURE_ENABLED=false
IS_HERMES_ENABLED=true
