package com.facebook.react;

import android.app.Application;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import java.util.Arrays;
import java.util.ArrayList;

/**
 * Manually provided PackageList.
 *
 * In a standard React Native project this file is auto-generated by the
 * GenerateAutolinkingPackageListTask from @react-native/gradle-plugin.
 * Since that task requires ReactSettingsPlugin (absent in 0.73.4), we
 * provide it statically here. Keep in sync with package.json native deps.
 *
 * Native modules are compiled as subprojects declared in settings.gradle.
 */
public class PackageList {

    private final ReactNativeHost reactNativeHost;

    public PackageList(ReactNativeHost reactNativeHost) {
        this.reactNativeHost = reactNativeHost;
    }

    /** Kept for API compatibility (Application constructor). */
    public PackageList(Application application) {
        this.reactNativeHost = null;
    }

    public ArrayList<ReactPackage> getPackages() {
        return new ArrayList<>(Arrays.asList(
            new MainReactPackage(),
            new com.th3rdwave.safeareacontext.SafeAreaContextPackage(),
            new com.swmansion.rnscreens.RNScreensPackage(),
            new com.swmansion.gesturehandler.RNGestureHandlerPackage(),
            new com.swmansion.reanimated.ReanimatedPackage(),
            new com.reactnativecommunity.asyncstorage.AsyncStoragePackage(),
            new com.oblador.vectoricons.VectorIconsPackage(),
            new com.reactnativecommunity.netinfo.NetInfoPackage()
        ));
    }
}
